plugins {
    id 'com.android.application'
}

android {
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildToolsVersion = '36.0.0'
    compileSdk = 37
    defaultConfig {
        applicationId "com.nikolaiapps.orbtrack"
        minSdkVersion 23
        targetSdkVersion 37
        versionName '3.5.12'
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
        versionCode 77
    }
    buildTypes {
        debug {
            jniDebuggable true
            applicationIdSuffix ".test"
        }
        release {
            jniDebuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles 'proguard-rules.pro'
        }
    }
    configurations {
        configureEach {
            exclude module: 'commons-logging'
            exclude module: 'httpclient'
        }
    }
    configurations.implementation {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
    productFlavors {
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
            excludes += ['META-INF/INDEX.LIST']
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
    }
    namespace 'com.nikolaiapps.orbtrack'
}

allprojects {
    repositories {
        maven {
            url "https://maven.google.com"
        }
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.documentfile:documentfile:1.1.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.10.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'com.dropbox.core:dropbox-core-sdk:7.0.0'
    implementation 'com.dropbox.core:dropbox-android-sdk:7.0.0'
    implementation 'com.google.api-client:google-api-client:2.9.0'
    implementation 'com.google.api-client:google-api-client-android:2.9.0'
    implementation 'com.google.apis:google-api-services-drive:v3-rev20230822-2.0.0'
    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.39.0'
    implementation 'com.google.android.play:age-signals:0.0.3'
    implementation 'androidx.camera:camera-camera2:1.6.1'
    implementation 'androidx.camera:camera-lifecycle:1.6.1'
    implementation 'androidx.camera:camera-view:1.6.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation files('libs/WhirlyGlobeMaply.aar')

    //noinspection LoginCredentials
    implementation 'com.google.android.gms:play-services-auth:21.6.0'
    //noinspection LoginCredentials
    implementation 'androidx.credentials:credentials:1.6.0'
    //noinspection LoginCredentials
    implementation 'androidx.credentials:credentials-play-services-auth:1.6.0'

    //noinspection GradleDependency
    implementation 'com.google.android.libraries.places:places:4.4.1'
}
